Repository ISISComputingGroup/EPICS-galil, pull requests merged in 2020-09, with the labels that each got.

#42 Ticket5602 guides and apertures homing
  GalilSup/Db/Makefile
  GalilSup/Db/galil_Home_sans2d_aperture.gmc
  GalilSup/Db/galil_Home_sans2d_waveguides.gmc
Labels: size/L

#41 Print position prior to applying home
  GalilSup/src/GalilAxis.cpp
Labels: size/XS

#44 Configure serial timeout
  GalilSup/src/GalilController.cpp
Labels: size/XS

#43 SANS2D: Added limit switch subroutine for front and rear axes
  GalilSup/Db/Makefile
  GalilSup/Db/galil_sans2d_front_det_limit_footer.gmc
  GalilSup/Db/galil_sans2d_rear_det_limit_footer.gmc
Labels: size/M

#45 Fix home of rear detector
  GalilSup/Db/galil_Home_sans2d_rear_detector.gmc
Labels: size/M
